# Generated by Django 3.1 on 2021-11-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='adress_line_2',
            new_name='address_line_2',
        ),
    ]
